import { Theme } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Slide, ToastContainer } from 'react-toastify';
import './globals.css';
import { ProgressBar } from './ProgressBar';
import QueryProvider from './QueryProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: '조인하와이 관리자 대시보드',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <QueryProvider>
          <Theme>{children}</Theme>
        </QueryProvider>
        <ToastContainer position='top-center' hideProgressBar transition={Slide} theme='colored' />
        <ProgressBar />
      </body>
    </html>
  );
}
